// This file is generated by rust-protobuf 2.18.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `src/proto/stdio.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_2;

#[derive(PartialEq,Clone,Default)]
pub struct StdioData {
    // message fields
    pub channel: StdioData_Channel,
    pub data: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a StdioData {
    fn default() -> &'a StdioData {
        <StdioData as ::protobuf::Message>::default_instance()
    }
}

impl StdioData {
    pub fn new() -> StdioData {
        ::std::default::Default::default()
    }

    // .plugin.StdioData.Channel channel = 1;


    pub fn get_channel(&self) -> StdioData_Channel {
        self.channel
    }
    pub fn clear_channel(&mut self) {
        self.channel = StdioData_Channel::INVALID;
    }

    // Param is passed by value, moved
    pub fn set_channel(&mut self, v: StdioData_Channel) {
        self.channel = v;
    }

    // bytes data = 2;


    pub fn get_data(&self) -> &[u8] {
        &self.data
    }
    pub fn clear_data(&mut self) {
        self.data.clear();
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data
    }

    // Take field
    pub fn take_data(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for StdioData {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.channel, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.channel != StdioData_Channel::INVALID {
            my_size += ::protobuf::rt::enum_size(1, self.channel);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.channel != StdioData_Channel::INVALID {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.channel))?;
        }
        if !self.data.is_empty() {
            os.write_bytes(2, &self.data)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> StdioData {
        StdioData::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<StdioData_Channel>>(
                "channel",
                |m: &StdioData| { &m.channel },
                |m: &mut StdioData| { &mut m.channel },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "data",
                |m: &StdioData| { &m.data },
                |m: &mut StdioData| { &mut m.data },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<StdioData>(
                "StdioData",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static StdioData {
        static instance: ::protobuf::rt::LazyV2<StdioData> = ::protobuf::rt::LazyV2::INIT;
        instance.get(StdioData::new)
    }
}

impl ::protobuf::Clear for StdioData {
    fn clear(&mut self) {
        self.channel = StdioData_Channel::INVALID;
        self.data.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for StdioData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StdioData {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum StdioData_Channel {
    INVALID = 0,
    STDOUT = 1,
    STDERR = 2,
}

impl ::protobuf::ProtobufEnum for StdioData_Channel {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<StdioData_Channel> {
        match value {
            0 => ::std::option::Option::Some(StdioData_Channel::INVALID),
            1 => ::std::option::Option::Some(StdioData_Channel::STDOUT),
            2 => ::std::option::Option::Some(StdioData_Channel::STDERR),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [StdioData_Channel] = &[
            StdioData_Channel::INVALID,
            StdioData_Channel::STDOUT,
            StdioData_Channel::STDERR,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<StdioData_Channel>("StdioData.Channel", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for StdioData_Channel {
}

impl ::std::default::Default for StdioData_Channel {
    fn default() -> Self {
        StdioData_Channel::INVALID
    }
}

impl ::protobuf::reflect::ProtobufValue for StdioData_Channel {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15src/proto/stdio.proto\x12\x06plugin\x1a\x1asrc/proto/controller.pr\
    oto\"\x84\x01\n\tStdioData\x123\n\x07channel\x18\x01\x20\x01(\x0e2\x19.p\
    lugin.StdioData.ChannelR\x07channel\x12\x12\n\x04data\x18\x02\x20\x01(\
    \x0cR\x04data\".\n\x07Channel\x12\x0b\n\x07INVALID\x10\0\x12\n\n\x06STDO\
    UT\x10\x01\x12\n\n\x06STDERR\x10\x022>\n\tGRPCStdio\x121\n\x0bStreamStdi\
    o\x12\r.plugin.Empty\x1a\x11.plugin.StdioData0\x01b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
